# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile --ignore-scripts

# Bundle app source
COPY . .

# Expose port if needed (though stdio doesn't need it, but may be used in dev)
EXPOSE 8788

# Run the MCP server via stdio transport
CMD ["npm", "run", "start:stdio"]
